### ISSUE TITLE
Move spacewalk CI to cloud

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/spacewalk#419] opened 2023-10-13 06:19 UTC
Running our CI workflows with the default/free-tier Github runners makes us wait for about 70-120 minutes per job. This is not ideal and we should try executing these CI jobs on a different platform/server that is more powerful than the basic Github runners. 

To achieve this, we can rent a high-spec server and dedicate it to running these CI jobs for us. For example, we could use the Cloud VPS XL server by [Contabo](https://contabo.com/en/vps/).

**Comment by ebma** [comment] 2023-10-13 09:05
@zoveress I discussed this topic with the tech team and we agreed that it might make sense to do this, under the assumption that it does not require too much effort for the core team to set this up. Let me know what input you need from the tech team for this.

**Comment by zoveress** [comment] 2023-10-13 10:02
@ebma the core team has no action to take here I will need to know what sort of tests and builds you would like to run and I will move them to gitlab using a high performance contabo server,

**Comment by ebma** [comment] 2023-10-13 12:21
Okay perfect. We want to have the commands contained in [this](https://github.com/pendulum-chain/spacewalk/blob/main/.github/workflows/ci-main.yml) workflow. 
So, assuming the required dependencies are installed, the commands for the CI are:
```
cargo build --all-features
cargo test --all --all-features
cargo fmt --all -- --check
cargo clippy --all-features -- -W clippy::all -A clippy::style -A clippy::forget_copy -A clippy::forget_ref
cargo clippy -all-features --all-targets -- -A clippy::all -W clippy::correctness -A clippy::forget_copy -A clippy::forget_ref
```

**Comment by zoveress** [comment] 2023-10-16 13:29
I am getting this:

`test runner::tests::test_runner_binary_is_not_redownloaded ... ok
test runner::tests::test_runner_delete_downloaded_release ... ok
test runner::tests::test_runner_child_restarts_if_crashed ... ok
test runner::tests::test_runner_nonexistent_binary_prompts_download ... ok
test runner::tests::test_runner_loading_binary_fails ... ok
test runner::tests::test_runner_different_checksum_prompts_download ... ok
test runner::tests::test_runner_terminate_child_process_does_not_throw ... ok
test runner::tests::test_runner_invalid_binary_prompts_download ... ok
test runner::tests::test_runner_terminate_child_proc_on_crash ... ok
test runner::tests::test_runner_get_bin_path ... ok
test runner::tests::test_try_load_downloaded_binary_checks_checksum ... ok
test runner::tests::test_runner_loading_existing_binary_works ... ok
test runner::tests::test_runner_run_binary_with_retry ... ok
test runner::tests::test_runner_terminate_child_proc_on_signal ... ok
test runner::tests::test_runner_terminate_proc_and_wait ... ok
test runner::tests::test_runner_download_binary has been running for over 60 seconds
test runner::tests::test_runner_download_binary ... FAILED

failures:

---- runner::tests::test_runner_download_binary stdout ----
thread 'runner::tests::test_runner_download_binary' panicked at 'called `Result::unwrap()` on an `Err` value: IncorrectChecksum', clients/runner/src/runner.rs:734:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    runner::tests::test_runner_download_binary

test result: FAILED. 15 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 60.08s

error: test failed, to rerun pass `-p runner --bin runner`
section_end:1697461921:step_script
[0Ksection_start:1697461921:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1697461921:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit status 1
[0;m`

**Comment by zoveress** [comment] 2023-10-16 13:31
I am getting the issue above any suggestions?

**Comment by ebma** [comment] 2023-10-17 13:31
@zoveress this issue should be fixed now that we merged #424.

**Comment by TorstenStueber** [comment] 2023-12-16 18:26
@zoveress can you confirm that the issues are fixed?

**Comment by zoveress** [comment] 2023-12-17 02:49
@TorstenStueber one last thing I have to do and then we are done. The problem is the way I call the release pipeline must be changed as it isn't calling it properly.

**Comment by TorstenStueber** [comment] 2024-04-04 05:21
@zoveress has this been completed by now?

**Comment by zoveress** [comment] 2024-04-04 05:33
Yes this has also been done.

**Closed** 2024-04-04 05:49 UTC
Labels: ci, type:dev-ops
